server:
  port: 8000
spring:
  application:
    name: cambio-service
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/cambio_service?useTimezone=true&serverTimezone=UTC
    username: root
    password: root
  flyway:
    url: jdbc:mysql://localhost:3306
    schemas: cambio_service
    user: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
  sleuth:
    sampler:
      probability: 1.0
  #zipkin:
    #base-url: http://localhost:9411/
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
springdoc:
  show-actuator: false
  api-docs:
    path: cambio/v3/api-docs
management:
  endpoints:
    web:
      cors:
        allowed-origins:
        - http://localhost:8765